### ISSUE TITLE
Chart not available anymore

### ISSUE THREAD

**Issue by splattner** [piccobit/cert-manager-webhook-hosttech#29]
Is the Helm chart (and this project) still maintained?

I'm getting an error recently when pulling the Helm chart:

```
helm pull https://piccobit.github.io/helm-charts cert-manager-webhook-hosttech
Error: Get "https://www.golang.page/helm-charts": dial tcp 213.145.228.113:443: connect: connection refused
```

**Comment by piccobit** [comment]
Apologies for the problems, I had given up the `golang.page` domain and didn't remember I had used it also as a GitHub page.

Please use now the following command to pull the Helm chart:

```
helm pull https://stich.io/helm-charts cert-manager-webhook-hosttech
```

**Comment by splattner** [comment]
awesome, thanks for the new repo url! I was able to pull again!
